apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: adservice-istio-client-mtls
spec:
  host: adservice.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: cartservice-istio-client-mtls
spec:
  host: cartservice.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: checkoutservice-istio-client-mtls
spec:
  host: checkoutservice.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: currencyservice-istio-client-mtls
spec:
  host: currencyservice.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: emailservice-istio-client-mtls
spec:
  host: emailservice.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: paymentservice-istio-client-mtls
spec:
  host: paymentservice.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: productcatalogservice-istio-client-mtls
spec:
  host: productcatalogservice.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: shippingservice-istio-client-mtls
spec:
  host: shippingservice.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: recommendationservice-istio-client-mtls
spec:
  host: recommendationservice.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: frontend-istio-client-mtls
spec:
  host: frontend.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: frontend-ingress-istio-client-mtls
spec:
  host: frontend-ingress.hipstershop.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---

apiVersion: "networking.istio.io/v1alpha3"
kind: DestinationRule
metadata:
  name: currency-external-istio-client-mtls
spec:
  host: currency-provider-external
  trafficPolicy:
    tls:
      mode: DISABLE
