apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: currency-policy
spec:
  targets:
  - name: www.ecb.europa.eu
  peers:
  - mtls:
      mode: PERMISSIVE

---

apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: currency-policy
spec:
  targets:
  - name: currency-provider-external
  peers:
  - mtls:
      mode: PERMISSIVE
