# adservice
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: adservice-policy
spec:
  targets:
  - name: adservice
  peers:
  - mtls:
      mode: PERMISSIVE


---
# cartservice
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: cartservice-policy
spec:
  targets:
  - name: cartservice
  peers:
  - mtls:
      mode: PERMISSIVE


---
# checkoutservice
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: checkoutservice-policy
spec:
  targets:
  - name: checkoutservice
  peers:
  - mtls:
      mode: PERMISSIVE

---

# currencyservice
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: currencyservice-policy
spec:
  targets:
  - name: currencyservice
  peers:
  - mtls:
      mode: PERMISSIVE



---
# emailservice
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: emailservice-policy
spec:
  targets:
  - name: emailservice
  peers:
  - mtls:
      mode: PERMISSIVE

---
# paymentservice
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: paymentservice-policy
spec:
  targets:
  - name: paymentservice
  peers:
  - mtls:
      mode: PERMISSIVE


---
# productcatalogservice
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: productcatalogservice-policy
spec:
  targets:
  - name: productcatalogservice
  peers:
  - mtls:
      mode: PERMISSIVE

---
# shippingservice
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: shippingservice-policy
spec:
  targets:
  - name: shippingservice
  peers:
  - mtls:
      mode: PERMISSIVE

---
# recommendationservice
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: recommendationservice-policy
spec:
  targets:
  - name: recommendationservice
  peers:
  - mtls:
      mode: PERMISSIVE

---
# frontend
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: frontend-policy
spec:
  targets:
  - name: frontend
  peers:
  - mtls:
      mode: PERMISSIVE


---
# frontend-ingress
apiVersion: "authentication.istio.io/v1alpha1"
kind: Policy
metadata:
  name: frontend-ingress-policy
spec:
  targets:
  - name: frontend-ingress
  peers:
  - mtls:
      mode: PERMISSIVE
