apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: currency-policy
spec:
  targets:
  - name: www.ecb.europa.eu
  peers:
  - mtls:
      mode: PERMISSIVE

---

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: frontend-policy
spec:
  selector:
    matchLabels:
      name: currency-provider-external
  mtls:
    mode: PERMISSIVE