apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: authorization
  namespace: default
spec:
  mtls:
    mode: STRICT
---
# frontend-ingress
apiVersion: security.istio.io/v1beta1
kind: "PeerAuthentication"
metadata:
  name: frontend-policy
spec:
  selector:
    matchLabels:
      name: frontend-ingress
  mtls:
    mode: PERMISSIVE