apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
    version: "1"
  ports:
  - name: http
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: frontend2
spec:
  type: ClusterIP
  selector:
    app: frontend
    version: "2"
  ports:
  - name: http
    port: 80
    targetPort: 8080
