apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: frontend-weights
spec:
  service: frontend-external
  backends:
  - service: frontend
    weight: 100m
  - service: frontend2
    weight: 900m