apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: deny-currency-service
  namespace: istio-system
spec:
  match: destination.service=="currencyservice.default.svc.cluster.local"
  actions: 
  - handler: deny.denier
    instances:
    - denyrequest.checknothing