apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: mixer-deny-curl
  namespace: istio-system
spec:
  match: match(request.headers["user-agent"], "curl*")
  actions:
  - handler: deny.denier
    instances:
    - denyrequest.checknothing