apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-ingress
spec:
  hosts:
  - "*"
  gateways:
  - frontend-gateway
  http:
  - route:
    - destination:
        host: frontend
        subset: v1
        port:
          number: 80
      weight: 90
    - destination:
        host: frontend
        subset: v2
        port:
          number: 80
      weight: 10