# https://istio.io/docs/reference/config/installation-options/

grafana:
  enabled: true
tracing:
  enabled: true
kiali:
  enabled: true
  tag: v1.4.2 
pilot:
  traceSampling: 100.0
global:
  controlPlaneSecurityEnabled: true
