apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: cartservice.default.svc.cluster.local
  namespace: default
spec:
  routes:
  - condition:
      method: POST
      pathRegex: /hipstershop\.CartService/AddItem
    name: POST CartService AddItem
  - condition:
      method: POST
      pathRegex: /hipstershop\.CartService/EmptyCart
    name: POST CartService EmptyCart
  - condition:
      method: POST
      pathRegex: /hipstershop\.CartService/GetCart
    name: POST CartService GetCart