apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: productcatalogservice.linkerd-demos.svc.cluster.local
  namespace: linkerd-demos
spec:
  routes:
  - condition:
      method: POST
      pathRegex: /hipstershop\.ProductCatalogService/GetProduct
    name: POST /hipstershop.ProductCatalogService/GetProduct
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /hipstershop\.ProductCatalogService/ListProducts
    name: POST /hipstershop.ProductCatalogService/ListProducts
    isRetryable: true
  retryBudget:
    ttl: 10s # innerhalb von 10 Sekunden
    retryRatio: 0.1 # dürfen 10% der Anfragen aus Retries bestehen
    minRetriesPerSecond: 5 # ab 5 Retries pro Sekunde wird gezählt