apiVersion: linkerd.io/v1alpha1
kind: ServiceProfile
metadata:
  name: productcatalogservice.default.svc.cluster.local
  namespace: default
spec:
  routes:
  - condition:
      method: POST
      pathRegex: /hipstershop\.ProductCatalogService/GetProduct
    name: POST /hipstershop.ProductCatalogService/GetProduct
  - condition:
      method: POST
      pathRegex: /hipstershop\.ProductCatalogService/ListProducts
    name: POST /hipstershop.ProductCatalogService/ListProducts
