apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: recommendationservice
spec:
  host: recommendationservice
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100 # maximal 100 TCP-Verbindungen
      http:
        maxRequestsPerConnection: 10  # maximal 10 HTTP-Requests pro Verbindung
        http1MaxPendingRequests: 1024 # maximal 1024 pending HTTP-Requests
    outlierDetection:
      consecutiveErrors: 5  # maximal 5 aufeinander folgende Fehler ...
      interval: 10s  # ... innerhalb von 10 Sekunden
      baseEjectionTime: 2m  # ansonsten pausiert der Service 2 Minuten
      maxEjectionPercent: 100  # 100% der pods sollen pausiert werden
