apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend
spec:
  host: frontend
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1 # maximal 1 TCP-Verbindung
      http:
        maxRequestsPerConnection: 1  # maximal 1 HTTP-Requests pro Verbindung
        http1MaxPendingRequests: 1 # maximal 1 pending HTTP-Requests
    outlierDetection:
      consecutiveErrors: 1  # maximal 1 aufeinander folgender Fehler ...
      interval: 1s  # ... innerhalb von 1 Sekunde
      baseEjectionTime: 1m  # ansonsten pausiert der Service für 1 Minute
      maxEjectionPercent: 100  # 100% der Pods sollen pausiert werden
