apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: recommendationservice
spec:
  hosts:
  - recommendationservice
  http:
  - route:
    - destination:
        host: recommendationservice
    fault:
      abort:
        percent: 50
        httpStatus: 500