apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: recommendationservice
spec:
  hosts:
  - recommendationservice
  http:
  - route:
    - destination:
        host: recommendationservice
        port:
          number: 8080
    retries:
      attempts: 3
      perTryTimeout: 1s
    timeout: 3s