apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: frontend-ingress
spec:
  hosts:
  - "*"
  http:
  - name: "frontend"
    route:
    - destination:
        host: frontend
        port:
          number: 80
