apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: promhttp
  namespace: istio-system
spec:
  match: "true"
  actions:
  - handler: handler.prometheus
    instances:
    - anfragedauer.metric.istio-system
    - anfrageanzahl.metric.istio-system